### ISSUE TITLE
Pause Network only pauses downloads

### ISSUE THREAD

**Issue by hansr** [diodechain/dDrive_Alpha_Program#18] opened 2020-12-23 08:04 UTC
MacOS 10.15.4, dDrive version 0.7.2-12

**Description:**
When I've added new content to a drive, it begins uploading to peers.  However, when I click "Pause Network", the peers are still able to download from my main peer.  I have to stop the remote peers in order to free my upload bandwidth.

**Steps to reproduce:**
- Create a Drive
- Add a remote Peer
- Add a large file
- Observe both owner and remote Peer begin syncing file (owner: upload; remote Peer: download)
- Click "Pause Network" on owner
- Observe remote Peer continues to download files until complete

**Desired Behavior:**
- Whatever Drive is "Paused" immediately stops downloading and uploading files

**Comment by dominicletz** [comment] 2021-01-07 15:00
@hansr let's talk about this, I can't reproduce

**Comment by dominicletz** [comment] 2021-01-14 15:44
Closing for now until repro

**Closed by dominicletz** 2021-01-14 15:44 UTC
Labels: bug
